### ISSUE TITLE
when will u update to the v3? 

### ISSUE THREAD

**Issue by nirmind24** [FireHead90544/craiyon.py#11]
hello! can u please update to the v3 models?

**Comment by mdm9300404** [comment]
We are already working on craiyon.py 0.4.0, which will support the v3 model.

It should be released hopefully sometime soon.

**Comment by nirmind24** [comment]
thanks)

**Comment by zentixua** [comment]
Thanks. We are waiting 🐱

**Comment by FireHead90544** [comment]
Hello, @nirmind24 @GenifeUA !
We just released the v1.0.0 that supports the new v3 model on [PyPI](https://pypi.org/project/craiyon.py/1.0.0/) and github as well.

**Comment by nirmind24** [comment]
> Hello, @nirmind24 @GenifeUA ! We just released the v1.0.0 that supports the new v3 model on [PyPI](https://pypi.org/project/craiyon.py/1.0.0/) and github as well.

thanks
