### ISSUE TITLE
The method Craiyon.generate() should return GeneratedImages(resp.json().get('images'))

### ISSUE THREAD

**Issue by matteobovio** [FireHead90544/craiyon.py#5]
At the moment, the method returns `GeneratedImages(resp.json())`. 
However, the response from the server is a json where the array of images (required by the class `GeneratedImages`) is under `images`.

**Comment by FireHead90544** [comment]
Will fix it in the next update, as soon as my exams finishes.

**Comment by FireHead90544** [comment]
Fixed it in the [v0.2.0](https://pypi.org/project/craiyon.py/0.2.0/) which is released on PyPI as well.
Run `pip install -U craiyon` to upgrade to the latest version :D
